function [file] = CT_ExptList_v6()
%% File Description
%   Generates a GUI for selecting worm tracks for anaylsis by Manual_WormTracks.m
%
%   Import variables from the Index sheet
%
%   Version 6.0
%   Version Date: 12/2/19
%
%%  Revision History
%   ~2017       Generated by ASB
%   8-27-19     Cleaned up and updated by ASB
%   9-24-19     Renamed v5 by ASB
%   12/2/19     Renamed v6 by ASB, added 2 more assay types and switched to
%               listdlg 

%% Get user to select the file to be analyzed.
% Switched to using uigetfile version, rather than specifying a dataset
% file. This seems like it will be more flexible.

[name, pathstr] = uigetfile('*.xlsx');
if isequal(name,0)
    error('User canceled analysis session');
else
    disp(['User selected ', fullfile(pathstr,name)]);
end

file.CL = fullfile(pathstr, name);

%% Determine the type of chemotaxis assay being analyzed

global assaytype % make the variable assaytype a global variable, so I can retreive it from any function, without passing it through the input/output calls.

[selection, ok] = listdlg('Name','Select Assay Type',...
    'PromptString','Pick a chemotaxis assay type',...
    'ListString',{'Bacterial Assay (4.9 cm arena)'; 'CO2 Assay (3.75 cm arena)'; 'Pheromone Assay (5 cm arena)';'Odor Assay (5 cm arena)'},...
    'SelectionMode','single','ListSize',[200 150]);
% Handle response
if ok < 1
    error('User canceled analysis session');
end

switch selection
    case 1
        assaytype = 1;
    case 2
        assaytype = 2;
    case 3
        assaytype = 3;  
    case 4
        assaytype = 4;     
end
